export const SET_SIDE_MODAL_STATE = 'SET_SIDE_MODAL_STATE';
export const SET_CENTER_MODAL_STATE = 'SET_CENTER_MODAL_STATE';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_SHOW_SIDE_NAV = 'SET_SHOW_SIDE_NAV';
export const SET_REDIRECT = 'SET_REDIRECT';
