import { createActionTypes } from '../../helpers';

export const FETCH_PROMOTIONS = createActionTypes('FETCH_PROMOTIONS');
export const CREATE_PROMOTION = createActionTypes('CREATE_PROMOTION');
export const UPDATE_PROMOTION = createActionTypes('UPDATE_PROMOTION');

export const CLEAR_PROMOTIONS = 'CLEAR_PROMOTIONS';
export const SET_ADD_PROMOTION_DETAILS_PAYLOAD = 'SET_ADD_PROMOTION_DETAILS_PAYLOAD';
export const SET_ADD_PROMOTION_CLAIMS_PAYLOAD = 'SET_ADD_PROMOTION_CLAIMS_PAYLOAD';
export const SET_ADD_PROMOTION_STEPS_PAYLOAD = 'SET_ADD_PROMOTION_STEPS_PAYLOAD';
export const SET_ADD_PROMOTION_CONDITION_PAYLOAD = 'SET_ADD_PROMOTION_CONDITION_PAYLOAD';
export const SET_ADD_PROMOTION_ELIGIBILITY_AND_FAQS = 'SET_ADD_PROMOTION_ELIGIBILITY_AND_FAQS';
